### ISSUE TITLE
License

### ISSUE THREAD

**Issue by LyzardKing** [Sadi58/grive-indicator#1]
Hi!
I noticed that grive-indicator and indicator-drive are missing a license.
I forked grive-indicator a while back, so I would like to know what the license is.
Thank you.

**Comment by Sadi58** [comment]
@LyzardKing Thanks for asking, but I personally have no interest in such legal stuff, at least as far as such very very modest contributions are concerned. After all what I have done is to write several lines of script (even some of them are borrowed from different sources on internet). So I don't even claim ownership on them.
However, software such as grive, etc. that some of such scripts I've written might have licensing aspects...
